// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordBuddy.Progress.Infrastructure.Persistence;

#nullable disable

namespace WordBuddy.Progress.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProgressDbContext))]
    [Migration("20260924084632_AddVocabularyRecall")]
    partial class AddVocabularyRecall
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WordBuddy.Progress.Domain.LearnerProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ScorePercent")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LessonId")
                        .IsUnique();

                    b.ToTable("LearnerProgressEntries", (string)null);
                });

            modelBuilder.Entity("WordBuddy.Progress.Domain.VocabularyRecallSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CheckedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WordsChecked")
                        .HasColumnType("int");

                    b.Property<int>("WordsKnown")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CheckedAtUtc");

                    b.ToTable("VocabularyRecallSessions", (string)null);
                });

            modelBuilder.Entity("WordBuddy.Progress.Domain.VocabularyRecallStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastCheckedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TimesChecked")
                        .HasColumnType("int");

                    b.Property<int>("TimesKnown")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VocabularyWordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "VocabularyWordId")
                        .IsUnique();

                    b.ToTable("VocabularyRecallStats", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
