apiVersion: v1
kind: ConfigMap
metadata:
  name: wordbuddy-config
  namespace: wordbuddy
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  Jwt__Issuer: "WordBuddy"
  Jwt__ExpiryMinutes: "60"
  FileStorage__BasePath: "/app/media"
