namespace WordBuddy.Content.Domain;

/// <summary>How a <see cref="Sense"/>'s content was produced. Stored as a string.</summary>
public enum SenseOrigin
{
    /// <summary>Written by a person (admin lesson word or learner word).</summary>
    Manual,

    /// <summary>Generated by the vocabulary auto-fill (dictionary + Claude). Children see it only
    /// after a supporter or admin approval.</summary>
    AutoFill
}
