// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordBuddy.Content.Infrastructure.Persistence;

#nullable disable

namespace WordBuddy.Content.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ContentDbContext))]
    [Migration("20261002174303_DropVocabularyWordIdRemaps")]
    partial class DropVocabularyWordIdRemaps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WordBuddy.Content.Domain.DailyPhrase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AudioAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phrase")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("VideoAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AudioAssetId");

                    b.HasIndex("LessonId");

                    b.HasIndex("VideoAssetId");

                    b.ToTable("DailyPhrases", (string)null);
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.GrammarRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Examples")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("GrammarRules", (string)null);
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TargetAgeGroup")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Lessons", (string)null);
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.LessonVocabularyWord", b =>
                {
                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VocabularyWordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("LessonId", "VocabularyWordId");

                    b.HasIndex("VocabularyWordId");

                    b.ToTable("LessonVocabularyWords", (string)null);
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("MediaAssets", (string)null);
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.UserVocabularyWord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAuthor")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VocabularyWordId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyWordId");

                    b.HasIndex("UserId", "VocabularyWordId")
                        .IsUnique();

                    b.ToTable("UserVocabularyWords", (string)null);
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.VocabularyWord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AudioAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Example")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ModeratedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModeratedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedWord")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerAgeGroup")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShareStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("VisibleToChildren")
                        .HasColumnType("bit");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AudioAssetId");

                    b.HasIndex("ContentHash");

                    b.HasIndex("NormalizedWord");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("ShareStatus");

                    b.HasIndex("ContentHash", "OwnerUserId")
                        .IsUnique()
                        .HasDatabaseName("UX_VocabularyWords_ContentHash_OwnerUserId_Learner")
                        .HasFilter("[Source] = 'Learner'");

                    b.ToTable("VocabularyWords", (string)null);
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.DailyPhrase", b =>
                {
                    b.HasOne("WordBuddy.Content.Domain.MediaAsset", "Audio")
                        .WithMany()
                        .HasForeignKey("AudioAssetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("WordBuddy.Content.Domain.Lesson", null)
                        .WithMany("DailyPhrases")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordBuddy.Content.Domain.MediaAsset", "Video")
                        .WithMany()
                        .HasForeignKey("VideoAssetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Audio");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.GrammarRule", b =>
                {
                    b.HasOne("WordBuddy.Content.Domain.Lesson", null)
                        .WithMany("GrammarRules")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.LessonVocabularyWord", b =>
                {
                    b.HasOne("WordBuddy.Content.Domain.Lesson", null)
                        .WithMany("VocabularyWords")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordBuddy.Content.Domain.VocabularyWord", "VocabularyWord")
                        .WithMany()
                        .HasForeignKey("VocabularyWordId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("VocabularyWord");
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.UserVocabularyWord", b =>
                {
                    b.HasOne("WordBuddy.Content.Domain.VocabularyWord", "VocabularyWord")
                        .WithMany()
                        .HasForeignKey("VocabularyWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VocabularyWord");
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.VocabularyWord", b =>
                {
                    b.HasOne("WordBuddy.Content.Domain.MediaAsset", "Audio")
                        .WithMany()
                        .HasForeignKey("AudioAssetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Audio");
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.Lesson", b =>
                {
                    b.Navigation("DailyPhrases");

                    b.Navigation("GrammarRules");

                    b.Navigation("VocabularyWords");
                });
#pragma warning restore 612, 618
        }
    }
}
