// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordBuddy.Content.Infrastructure.Persistence;

#nullable disable

namespace WordBuddy.Content.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ContentDbContext))]
    [Migration("20261005023005_SplitVocabularyIntoLexemesAndSenses")]
    partial class SplitVocabularyIntoLexemesAndSenses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WordBuddy.Content.Domain.DailyPhrase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AudioAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phrase")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("VideoAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AudioAssetId");

                    b.HasIndex("LessonId");

                    b.HasIndex("VideoAssetId");

                    b.ToTable("DailyPhrases", (string)null);
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.GrammarRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Examples")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("GrammarRules", (string)null);
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.LearnerWord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Learner");

                    b.Property<bool>("IsAuthor")
                        .HasColumnType("bit");

                    b.Property<string>("PersonalContext")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SenseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SenseId");

                    b.HasIndex("UserId", "SenseId")
                        .IsUnique();

                    b.ToTable("LearnerWords", (string)null);
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TargetAgeGroup")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Lessons", (string)null);
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.LessonSense", b =>
                {
                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("LessonId", "SenseId");

                    b.HasIndex("SenseId");

                    b.ToTable("LessonSenses", (string)null);
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.Lexeme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CefrLevel")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FrequencyRank")
                        .HasColumnType("int");

                    b.Property<string>("IpaUk")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpaUs")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lemma")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedLemma")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PartOfSpeech")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Syllables")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("UkAudioAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UsAudioAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WordForms")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("N'[]'");

                    b.HasKey("Id");

                    b.HasIndex("UkAudioAssetId");

                    b.HasIndex("UsAudioAssetId");

                    b.HasIndex("NormalizedLemma", "PartOfSpeech")
                        .IsUnique()
                        .HasDatabaseName("UX_Lexemes_NormalizedLemma_PartOfSpeech");

                    b.ToTable("Lexemes", (string)null);
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("MediaAssets", (string)null);
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.Sense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AudioAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Example")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("LexemeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModeratedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModeratedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OwnerAgeGroup")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShareStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("VisibleToChildren")
                        .HasColumnType("bit");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AudioAssetId");

                    b.HasIndex("ContentHash");

                    b.HasIndex("LexemeId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("ShareStatus");

                    b.HasIndex("ContentHash", "OwnerUserId")
                        .IsUnique()
                        .HasDatabaseName("UX_Senses_ContentHash_OwnerUserId_Learner")
                        .HasFilter("[Source] = 'Learner'");

                    b.ToTable("Senses", (string)null);
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.SenseTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<Guid>("SenseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("SenseId", "Locale")
                        .IsUnique()
                        .HasDatabaseName("UX_SenseTranslations_SenseId_Locale");

                    b.ToTable("SenseTranslations", (string)null);
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.DailyPhrase", b =>
                {
                    b.HasOne("WordBuddy.Content.Domain.MediaAsset", "Audio")
                        .WithMany()
                        .HasForeignKey("AudioAssetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("WordBuddy.Content.Domain.Lesson", null)
                        .WithMany("DailyPhrases")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordBuddy.Content.Domain.MediaAsset", "Video")
                        .WithMany()
                        .HasForeignKey("VideoAssetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Audio");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.GrammarRule", b =>
                {
                    b.HasOne("WordBuddy.Content.Domain.Lesson", null)
                        .WithMany("GrammarRules")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.LearnerWord", b =>
                {
                    b.HasOne("WordBuddy.Content.Domain.Sense", "Sense")
                        .WithMany()
                        .HasForeignKey("SenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sense");
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.LessonSense", b =>
                {
                    b.HasOne("WordBuddy.Content.Domain.Lesson", null)
                        .WithMany("VocabularyWords")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordBuddy.Content.Domain.Sense", "Sense")
                        .WithMany()
                        .HasForeignKey("SenseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Sense");
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.Lexeme", b =>
                {
                    b.HasOne("WordBuddy.Content.Domain.MediaAsset", "UkAudio")
                        .WithMany()
                        .HasForeignKey("UkAudioAssetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("WordBuddy.Content.Domain.MediaAsset", "UsAudio")
                        .WithMany()
                        .HasForeignKey("UsAudioAssetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("UkAudio");

                    b.Navigation("UsAudio");
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.Sense", b =>
                {
                    b.HasOne("WordBuddy.Content.Domain.MediaAsset", "Audio")
                        .WithMany()
                        .HasForeignKey("AudioAssetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("WordBuddy.Content.Domain.Lexeme", null)
                        .WithMany()
                        .HasForeignKey("LexemeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Audio");
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.SenseTranslation", b =>
                {
                    b.HasOne("WordBuddy.Content.Domain.Sense", null)
                        .WithMany()
                        .HasForeignKey("SenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WordBuddy.Content.Domain.Lesson", b =>
                {
                    b.Navigation("DailyPhrases");

                    b.Navigation("GrammarRules");

                    b.Navigation("VocabularyWords");
                });
#pragma warning restore 612, 618
        }
    }
}
